apiVersion: v1
kind: Service
metadata:
  name: web-vote-app
spec:
  selector:
    app: web-vote-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: results-app
spec:
  selector:
    app: results-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: redis01
spec:
  selector:
    app: redis01
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-vote-app
  template:
    metadata:
      labels:
        app: web-vote-app
    spec:
      automountServiceAccountToken: false
      containers:
      - name: web-vote-app
        image: ray117/swarm-microservice-demo-v1-web-vote-app:latest
        env:
        - name: WEB_VOTE_NUMBER
          value: "01"
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-worker
  template:
    metadata:
      labels:
        app: vote-worker
    spec:
      automountServiceAccountToken: false
      containers:
      - name: vote-worker
        image: ray117/swarm-microservice-demo-v1-vote-worker:latest
        env:
        - name: FROM_REDIS_HOST
          value: "1"
        - name: TO_REDIS_HOST
          value: "1"
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: results-app
  template:
    metadata:
      labels:
        app: results-app
    spec:
      automountServiceAccountToken: false
      containers:
      - name: results-app
        image: ray117/swarm-microservice-demo-v1-results-app:latest
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis01
  template:
    metadata:
      labels:
        app: redis01
    spec:
      automountServiceAccountToken: false
      containers:
      - name: redis01
        image: ray117/redis:3
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      automountServiceAccountToken: false
      containers:
      - name: store
        image: ray117/postgres:9.5
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "pg8675309"
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
        ports:
        - containerPort: 5432