apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: vote-worker
  name: vote-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vote-worker
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/swarm-microservice-demo-v1-default: "true"
        io.kompose.service: vote-worker
    spec:
      containers:
        - env:
            - name: FROM_REDIS_HOST
              value: "1"
            - name: TO_REDIS_HOST
              value: "1"
          image: vote-worker
          name: vote-worker
      restartPolicy: Always
