apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: web-vote-app
  name: web-vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-vote-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/swarm-microservice-demo-v1-default: "true"
        io.kompose.service: web-vote-app
    spec:
      containers:
        - env:
            - name: WEB_VOTE_NUMBER
              value: "01"
            - name: CONSTRAINT_NODE
              value: =frontend01
          image: web-vote-app
          name: web-vote-app
          ports:
            - containerPort: 80
              hostPort: 8081
              protocol: TCP
      restartPolicy: Always
