apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: redis01
  name: redis01
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis01
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/swarm-microservice-demo-v1-default: "true"
        io.kompose.service: redis01
    spec:
      containers:
        - image: redis:3
          name: redis01
          ports:
            - containerPort: 6379
              hostPort: 6379
              protocol: TCP
      restartPolicy: Always
