apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: store
  name: store
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: store
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/swarm-microservice-demo-v1-default: "true"
        io.kompose.service: store
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: pg8675309
            - name: POSTGRES_USER
              value: postgres
          image: postgres:9.5
          name: store
      restartPolicy: Always
